# Generated by Django 2.1.5 on 2020-12-29 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='P_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('date_of_birth', models.DateTimeField()),
                ('height', models.SmallIntegerField()),
                ('rating', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('club_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Club_model')),
            ],
        ),
    ]
