# Generated by Django 2.1.5 on 2021-01-03 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player_info', '0003_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='link',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
