# Generated by Django 3.1.5 on 2021-01-05 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club_model',
            name='club_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
